### ISSUE TITLE
Listing removed from Google Chrome Webstore

### ISSUE THREAD

**Issue by yogeshbatra** [anthonyftwang/youtube-rabbit-hole#2]
Hello dev, 
your extension listing removed from google chrome webstore and google chrome now try to disable it(already installed ext) due to chrome web store policy showing this error in extension tab **This extension violates the Chrome Web Store policy.**

Thanks

**Comment by huciaa** [comment]
@yogeshbatra 
Is there a way to reinstall this extension?

**Comment by anthonyftwang** [comment]
Hi all, thanks for flagging this. I've made some changes that should resolve the issues, and resubmitted the listing for review. Will update this once I hear back.

**Comment by yogeshbatra** [comment]
> It's very sad. To install the extension locally you need to:
> 
> * download zipped repo and unpack / clone
> * go to settings > extension
> * turn on dev mode
> * pick "Load unpacked"
> * select this precious repo
> * you are happy again

that i know the extension is already installed in my browser and after google chrome disabling it i enable it and i am just doing my duty as a ext fan to alert dev for the issue.

**Comment by anthonyftwang** [comment]
Resolved - listing is [back up now](https://chrome.google.com/webstore/detail/rabbit-hole-for-youtube/nlddakjbmpidooplakalfoogdincflfh)! Thanks for the patience on this.
